const movie_detail = JSON.parse(localStorage.getItem("Movie_detail"));
if (!movie_detail) {
  localStorage.setItem(
    "Movie_detail",
    JSON.stringify([
      {
        actors: "Actors : Simbu,Sayeesha,Gautam karthik",
        dates: "",
        director: "Director : Krishna",
        genre: "Genre : Thriller",
        image_link:
          "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/pathu-thala-et00333005-1672646997.jpg",
        language: "Language : Tamil",
        link_file: "",
        movie_name: "PATHU THALA",
        music_Director: " Music Director : A.R. Rahman",
        synopsis:
          "Movie Description : Pathu Thala is a Tamil movie starring Silambarasan T. R. and Gautham Karthik in prominent roles. It is an action drama directed by Obeli N. Krishna and produced by Dr. Jayantilal Gada and K. E. Gnanavel Raja forming part of the crew.",
          morningTiming : "11:15",
          afternoonTiming : "01:15",
          eveningTiming : "04:15",
          theatreName:"Sundar Theatre",
        uuid: "de46612e-4ef2-4333-9fe5-9f15d4c955eb",
      },
      {
        actors: " Actors : Bill Skarsgard,John Leguizamo,Keanu Reeves",
        date: "",
        dates: "",
        director: "Chad Stahelski",
        genre: "Thriller",
        image_link:
          "https://i0.wp.com/fabukmagazine.com/wp-content/uploads/2023/02/JOHN-WICK-CHAPTER-4-Second-Trailer.jpg?resize=768%2C576&ssl=1",
        image_url: "undefined",
        language: "English",
        link_file: "",
        movie_name: "JOHN WICK CHAPTER-4",
        music_Director: "Tyler Bates",
        music_director: "Tyler Bates",
        synopsis:
          "John Wick (Keanu Reeves) takes on his most lethal adversaries yet in the upcoming fourth installment of the series. With the price on his head ever increasing, Wick takes his fight against the High Table global as he seeks out the most powerful players in the underworld, from New York to Paris to Osaka to Berlin.",
          morningTiming : "11:00",
          afternoonTiming : "02:00",
          eveningTiming : "05:15",
          theatreName : "Vetri Theatre",
        uuid: "55d10c81-ab23-48c9-9116-40256bf9df42",
      },
      {
        actors: "Ravi Teja,Magha Aakash",
        dates: "",
        director: "Sudheer Varma",
        genre: "Thriller",
        image_link:
          "https://moviegalleri.net/wp-content/uploads/2022/01/Ravi-Teja-Ravanasura-Movie-HD-Wallpaper.jpg",
        language: "Telugu",
        link_file: "",
        movie_name: "RAVANUSURA",
        music_Director: "Bheems Ceciroleo",
        synopsis:
          "Ravanasura is a drama film directed by Sudheer Varma, featuring Ravi Teja and Mandava Sai Kumar in prominent roles.",
          morningTiming : "11:30",
          afternoonTiming : "02:30",
          eveningTiming : "05:30",
          theatreName : "Rohini Theatre",
        timing: "",
        uuid: "52161c76-0519-4e62-9591-4e80bb656269",
      },
      {
        actors: "Vijay Sethupathi,Soori,Bhavani Sre",
        dates: "",
        director: "Vetri Maaran",
        genre: "Thriller",
        image_link:
          "https://www.newsbricks.com/root_upld/general-news/2023/03/40830/org_88836202303031632.jpg",
        language: "Tamil",
        link_file: "",
        movie_name: "VIDUTHALAI",
        music_Director: "Ilayaraja",
        synopsis:
          "Viduthalai is a Tamil movie starring Vijay Sethupathi and Soori in prominent roles. It is a drama directed by Vetrimaaran.",
          morningTiming : "11:15",
          afternoonTiming : "01:15",
          eveningTiming : "04:15",
          theatreName : "Radha Theatre",
        uuid: "b6e81045-7309-48e8-9e92-331bcbf99638",
      },
      {
        actors: "Dhananjay,Amrutha Iyengar",
        dates: "",
        director: "Vijay.N",
        genre: "Thriller",
        image_link:
          "https://assets-in.bmscdn.com/iedb/movies/images/mobile/listing/xxlarge/gurudev-hoysala-et00339422-1678799219.jpg",
        language: "Kanada",
        link_file: "",
        movie_name: "GURUDEV HOYSALA",
        music_Director: "B.Ajaneesh Loknath",
        synopsis:
          "Gurudev Hoysala, an upright police officer, is transferred to Athani to investigate a case of a fellow missing officer. While working on the case, a young couple is brought to the station by one of his subordinates suspecting them of foul play.",
          morningTiming : "12:15",
          afternoonTiming : "03:15",
          eveningTiming : "07:15",
          theatreName : "Jothi Theatre",
        uuid: "c39885b4-8e04-41e7-b9cd-a85fdec90302",
      },
      {
        actors: "Ajay Devgan,Raai Laxmi,Tabu Hashmi",
        dates: "",
        director: "Ajay Devgan",
        genre: "Thriller",
        image_link: "https://i.ytimg.com/vi/XYmRnpXUUdk/maxresdefault.jpg",
        language: "Hindi",
        link_file: "",
        movie_name: "BHOLAA",
        music_Director: "Mithun Sharma",
        synopsis:
          "Bhola, a prisoner, is finally going home after 10 years of imprisonment to meet his young daughter. His journey gets difficult when he is arrested mid-way. At first, he is not aware of the grave situation he has got himself into but after a crazy incident takes place, he must travel a pathway full of crazy obstacles with death lurking around every corner.",
          morningTiming : "11:15",
          afternoonTiming : "01:15",
          eveningTiming : "04:15",
          theatreName : "Mayajaal",
        uuid: "8686ac0a-07b3-42f0-b11a-05696df65aec",
      },
      {
        actors: "Jayam Ravi,Aishwarya Rai Bachchan,Trisha Krishnan",
        dates: "",
        director: "Mani Ratnam",
        genre: "Thriller",
        image_link:
          "https://images.indulgexpress.com/uploads/user/imagelibrary/2022/12/29/original/PonniyinSelvan2toreleaseonthisdatewatchteaserfeaturingAishwaryaRa.jpg",
        language: "Tamil",
        link_file: "",
        movie_name: "Ponniyian Selvam",
        music_Director: "AR Rahman",
        synopsis:
          "Directed by Mani Ratnam Ponniyin Selvan - Part 2 features Vikram, Karthi and Aishwarya Bachchan in prominent roles.",
          morningTiming : "10:00",
          afternoonTiming : "01:00",
          eveningTiming : "04:00",
          theatreName : "Pvr Cinemas",
        uuid: "4773b171-b02e-4756-bb9b-854e1fa4c7aa",
      },
      {
        actors: "Lawrence Raghavendra,Priya Bhavani Shankar",
        dates: "",
        director: "Kathireshan",
        genre: "Thriller",
        image_link: "https://static.toiimg.com/photo/94483777.cms?resizemode=4",
        language: "Tamil",
        link_file: "",
        movie_name: "RUDHRAN",
        music_Director: "GV Prakash Kumar",
        synopsis:
          "Rudhran is a Tamil movie starring Lawrence Raghavendra and Priya Bhavani Shankar in prominent roles. It is a drama directed by Kathireshan forming part of the crew.",
          morningTiming : "11:15",
          afternoonTiming : "02:15",
          eveningTiming : "05:15",
          theatreName : "Raj Theatre",
        uuid: "c64e3e2e-e02a-4aa0-92d9-e095a5b93412",
      },
    ])
  );
}